const { validationResult } = require("express-validator");
const ApiError = require("../utils/ApiError");

/**
 * Validation Middleware
 *
 * Checks validation errors generated by express-validator.
 * If validation fails, forwards a standardized ApiError
 * to the global error handler.
 */

const validateMiddleware = (req, res, next) => {
    const errors = validationResult(req);

    if (errors.isEmpty()) {
        return next();
    }

    const formattedErrors = errors.array().map((error) => ({
        field: error.path,
        message: error.msg,
        value: error.value,
    }));

    return next(
        ApiError.validation(
            "Validation Failed",
            formattedErrors
        )
    );
};

module.exports = validateMiddleware;